### ISSUE TITLE
Modded Modules

### ISSUE THREAD

**Issue by Zeen3** [KSPSnark/DefaultActionGroups#1]
Hey, I hope it's okay to ask for help here. I wanted to change and add some of the default settings of this mod so I looked up the syntax of the ModuleManager and how you used it in your files. (I'm quite new into KSP Modding) My goal was to add all Science experiments to Custom01 and the Reset to Custom03. Since I wanted it to be a bit more dynamic with other mods, this is my solution:

```
@PART[*]:HAS[@MODULE[*Science*]:HAS[#experimentActionName]] {
	@description ^= :(.)$:$0 Runs with Custom01.:
	MODULE {
		name = ModuleDefaultActionGroup
		moduleSource = #$../MODULE[*Science*]:HAS[#experimentActionName]/name$
		actionGuiName = #$../MODULE[*Science*]:HAS[#experimentActionName]/experimentActionName$
		defaultActionGroup = Custom01
	}
}

@PART[*]:HAS[@MODULE[*Science*]:HAS[#resetActionName]] {
	@description ^= :(.)$:$0 Resets with Custom03.:
	MODULE {
		name = ModuleDefaultActionGroup
		moduleSource = #$../MODULE[*Science*]:HAS[#resetActionName]/name$
		actionGuiName = #$../MODULE[*Science*]:HAS[#resetActionName]/resetActionName$
		defaultActionGroup = Custom03
	}
}
```

The Idea is that not all mods use the "ModuleScienceExperiment" e.g. the "DMagic Orbital Science" mod and it actually works quite well. Custom01 is full with stock and modded ScienceExperiments, but Custom03 has almost only the Stock Experiments. Note: The description still shows "Resets with Custom03" - so the game definitely found the parts and the ActionNames and edited the Part. ModuleManager has no errors and in the log it shows that it edited a lot of Parts. I also looked up the parts, and they definitely have a proper resetActionName. 

Do you have any idea why this isn't working properly? Does it matter that I'm using KSP 1.9? I think most mods for 1.8 are still compatible. (Besides those who use the old rendering.)

**Comment by KSPSnark** [comment]
Hi there!  Best place to ask for help with stuff is generally in the thread for the mod on the KSP forum, located here:
https://forum.kerbalspaceprogram.com/index.php?/topic/125832-18x-defaultactiongroups-v13-part-actions-automatically-in-the-action-group-of-your-choice/

That said:  You're getting pretty fancy with the ModuleManager stuff there, and I wouldn't be surprised if you're breaking some sort of boundary with your syntax.  I'm not any kind of encyclopedic MM expert myself-- I know it _moderately_ well, but only well enough to do the things I've needed to do myself.  If I had to guess... I'm not sure it's valid to use the :HAS blocks in the specification of moduleSource and actionGuiName, since I think that's a _filter_ and may only be valid in contexts where you're trying to winnow down the set of things to which a clause applies.

Happy to discuss further, but best to do it in the forum thread.  And this may actually be more of a ModuleManager question than a DefaultActionGroups question, but it's hard for me to tell at this point.
